Vagrant.configure("2") do |config|
    def define_vm(config, name, box_manager, ip_suffix)
      config.vm.define name do |vm| # Define nome a VM e configurações dentro dela.
        vm.vm.box = box_manager # Define a imagem da VM (Sistema Operacional).
        vm.vm.provider "virtualbox" do |vb| # Configurações específicas do virtualbox.
          vb.name = name # Nome da VM no virtualbox.
          vb.memory = 2048 # Define a memória RAM para 2GB
          vb.cpus = 2 # Define o número de CPUs(Processador)
        end
        # Configura a VM para usar a rede pública (equivalente a uma configuração de rede em modo bridge)
        vm.vm.network "public_network", ip: "192.168.1.#{ip_suffix}"
      end
    end

    # Hash com as boxes e gerenciadores de pacotes para diferentes distribuições Linux.
    rocky9_box = 'rockylinux/9'
    leap_box = 'opensuse/Leap-15.4.x86_64'
    
    # Servidores CodeLinxAcademy
    codelinx_vms = {
      'codelinx01' => rocky9_box,
      'codelinx02' => leap_box,
    }
   
    # Executa criação das VMs.
    ip_suffix = 201
    codelinx_vms.each do |name, box|
      define_vm(config, name, box, ip_suffix)
      ip_suffix += 1
    end
end